### ISSUE TITLE
Add djagged_vector type definition

### ISSUE THREAD

**Issue by beomki-yeo** [acts-project/algebra-plugins#23]
Algebra plugins is needed to define djagged_vector type (a.k.a. vector of vector) in [core/common/include/algebra/common/types.hpp](https://github.com/acts-project/algebra-plugins/blob/07cce703bad3382d77efe5b5c55a028188c3373d/core/common/include/algebra/common/types.hpp)

For example,
`djagged_vector <> = std::vector<std::vector<>>` for std library
`djagged_vector <> = vecmem::jagged_vector<>` for vecmem library

**Comment by paulgessinger** [comment]
Maybe I'm missing the point, but why would this be in **algebra**?

**Comment by niermann999** [comment]
The global container defs are handeled in the algebra plugins currently, because I needed overaligned allocators for some of the plugins. But I think c++17 allocators do that on their own now. I thought the utils/containers was simply not used anywhere anymore

**Comment by krasznaa** [comment]
That type was added, and since then removed from this project. I believe this can be closed. :stuck_out_tongue:
