### ISSUE TITLE
Arbitrary matrix definition in algebra plugin

### ISSUE THREAD

**Issue by beomki-yeo** [acts-project/algebra-plugins#40]
In acts-project/traccc#85, I used eigen matrix to define track parameter type.

```c++
template <unsigned int kSize>
using traccc_vector = Eigen::Matrix<scalar, kSize, 1>;

template <unsigned int kRows, unsigned int kCols>
using traccc_matrix = Eigen::Matrix<scalar, kRows, kCols>;

template <unsigned int kSize>
using traccc_sym_matrix = Eigen::Matrix<scalar, kSize, kSize>;
```

But I believe it is better to define them for different plguins. We can start from `std::array` I suppose.

**Comment by krasznaa** [comment]
:thinking: What matrix sizes are we talking about here? What types of operations should this repository provide on top of those matrices?

If we want to perform specific types of operations on those matrices, then yes, we should absolutely extend this project with that code. But if it's just a matter of type definitions, then we really shouldn't... There's a reason why I also removed the "vector types" from this project. As those were also only useful in the [detray](https://github.com/acts-project/detray) code. (And its clients.)

**Comment by beomki-yeo** [comment]
I am sorry that I don't have a clear picture. We should also discuss with @georgiana.
There are quite many matrix sizes we have to handle during the KF (2x2 7x8 6x6 6x7 2x6 1x6 possibly much more) and I don't think it is a good idea to write operations for each matrix size. So I want to ask if the generalized operation can be realized with `std::array`

The matrix operations we might need from this repository:
-  addition 
-  multiplication
-  transpose
-  inversion
-  symmetric property of matrix

**Comment by beomki-yeo** [comment]
Going further, I am really not sure if we have to put single-thread based KF and multi-thread based KF in to this project or in traccc

**Comment by georgi-mania** [comment]
Any matrix operation can be implemented with arrays. In fact, one performance optimization to the inverse implementation which reduced the overall time with an order of magnitude was to convert the eigen matrices into plain C arrays, work with them through the algorithm and then convert the result to eigen matrix type at the end. 
I agree with @beomki-yeo 's suggestion to have one implementation for each matrix operation rather than one for each matrix size.

**Comment by beomki-yeo** [comment]
Have we fully agreed on how to proceed? It's kinda getting urgent especially for `array` plugin which has nothing in terms of matrix operations
