### ISSUE TITLE
Add Matrix Operations

### ISSUE THREAD

**Issue by beomki-yeo** [acts-project/algebra-plugins#51]
We have introduced general matrix type with #50. Meanwhile, we still need following general matrix operations:
- Addition/Subtraction
- Multiplication
- Transpose
- Inversion
- Unit matrix generation
- Zero matrix generation

I wrote down as many operations as I can recall. There are possibly more :/ (I will keep updating the list)

It should be noted that we need to prioritize the operations for "general" size matrix.
Specialization or optimization for the specific dimensions should come later.

*) All above operations basically assume "one thread per one matrix (or track)" for device usage
We will need "one block per one matrix" operations as well some day

**Comment by HadrienG2** [comment]
Might as well add @paulgessinger , we have some plans to experiment around this during GSoC.
